server:
  port: 10006

spring:
  application:
    name: coating-filesystem

  # SpringMVC上传文件配置
  servlet:
    multipart:
      # 默认支持文件上传.
      enabled: true
      # 支持文件写入磁盘
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 10MB
      # 最大支持请求大小
      max-request-size: 30MB

#  data:
#    mongodb:
#      database: xc_fs
#      uri: mongodb://root:123@127.0.0.1:27017

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10000/eureka
  instance:
    prefer-ip-address: true


# 自定义的配置
fastdfs:
  connect_timeout_in_millisecond: 5000
  network_timeout_in_millisecond: 30000
  charset: UTF-8
  tracker_servers: 45.76.46.123:22122
  nginx_url: http://45.76.46.123:8888/  # 注意末尾要加上/ ，因为fastdfs返回的文件id开头没有/


